package com.xujiayao.discord_mc_chat.network.protocol;

import com.xujiayao.discord_mc_chat.network.message.TextSegment;

import java.util.ArrayList;
import java.util.Arrays;
import java.util.Base64;
import java.util.List;
import java.util.Map;

/**
 * All packets DMCC exchanges, as immutable records.
 * <p>
 * The record groups mirror the flows of the protocol: authentication, liveness, remote command execution,
 * runtime info, account linking and events.
 *
 * @author Xujiayao
 */
public final class Packets {

	private Packets() {
	}

	// --- Authentication --------------------------------------------------------------------------

	/**
	 * Sent by a client to initiate the connection.
	 *
	 * @param serverName       DMCC client/server name.
	 * @param dmccVersion      DMCC version of the sender.
	 * @param minecraftVersion Minecraft version of the sender environment.
	 */
	public record Handshake(String serverName, String dmccVersion, String minecraftVersion) implements Packet {
		@Override
		public PacketType type() {
			return PacketType.HANDSHAKE;
		}
	}

	/**
	 * Sent by the server to challenge the client.
	 *
	 * @param salt Random challenge salt generated by the server.
	 */
	public record Challenge(String salt) implements Packet {
		@Override
		public PacketType type() {
			return PacketType.CHALLENGE;
		}
	}

	/**
	 * Sent by the client with the hash computed from the challenge salt and the shared secret.
	 *
	 * @param hash SHA-256 hash of salt + shared secret.
	 */
	public record AuthResponse(String hash) implements Packet {
		@Override
		public PacketType type() {
			return PacketType.AUTH_RESPONSE;
		}
	}

	/**
	 * Sent by the server to confirm authentication and to push session settings.
	 *
	 * @param language                         Selected language code.
	 * @param overwriteMinecraftSourceMessages Whether Minecraft source messages should be overwritten.
	 * @param consoleForwardingEnabled         Whether console forwarding is enabled.
	 */
	public record LoginSuccess(String language, boolean overwriteMinecraftSourceMessages,
							   boolean consoleForwardingEnabled) implements Packet {
		@Override
		public PacketType type() {
			return PacketType.LOGIN_SUCCESS;
		}
	}

	/**
	 * Sent by either side to disconnect with a localized reason.
	 *
	 * @param key  Translation key of the disconnect reason.
	 * @param args Translation arguments.
	 */
	public record Disconnect(String key, String[] args) implements Packet {
		@Override
		public PacketType type() {
			return PacketType.DISCONNECT;
		}
	}

	// --- Liveness --------------------------------------------------------------------------------

	/**
	 * Keepalive heartbeat, resets the idle timer on the receiving side.
	 */
	public record KeepAlive() implements Packet {
		@Override
		public PacketType type() {
			return PacketType.KEEP_ALIVE;
		}
	}

	/**
	 * Active latency probe.
	 *
	 * @param sentAtMillis Sender timestamp in milliseconds.
	 */
	public record LatencyPing(long sentAtMillis) implements Packet {
		@Override
		public PacketType type() {
			return PacketType.LATENCY_PING;
		}
	}

	/**
	 * Active latency probe response.
	 *
	 * @param sentAtMillis Echoed sender timestamp in milliseconds.
	 */
	public record LatencyPong(long sentAtMillis) implements Packet {
		@Override
		public PacketType type() {
			return PacketType.LATENCY_PONG;
		}
	}

	// --- Remote command execution ----------------------------------------------------------------

	/**
	 * The remote execution flows that share the request/result shape.
	 */
	public enum RpcKind {
		/** Run a Minecraft command on a connected client. */
		CONSOLE,
		/** Run a DMCC command on a connected client. */
		EXECUTE,
		/** Ask the DMCC Server to run an update check. */
		UPDATE_CHECK
	}

	/**
	 * A remote execution request.
	 *
	 * @param kind      Which flow this request belongs to.
	 * @param requestId Correlation id echoed back in the {@link CommandResult}.
	 * @param opLevel   Requester's OP level, used for the receiving side's own permission check.
	 * @param input     Command line ({@code CONSOLE}/{@code UPDATE_CHECK}) or DMCC command name ({@code EXECUTE}).
	 * @param args      DMCC command arguments, only used by {@code EXECUTE}.
	 */
	public record CommandRequest(RpcKind kind, String requestId, int opLevel, String input,
								 String[] args) implements Packet {
		@Override
		public PacketType type() {
			return PacketType.COMMAND_REQUEST;
		}
	}

	/**
	 * The result of a {@link CommandRequest}.
	 * <p>
	 * File payloads (for example the log returned by {@code /log}) never travel inside this record: they are
	 * streamed as {@link CommandFileChunk} frames just before it, so a large file cannot exceed the 1 MiB
	 * frame limit and tear the connection down.
	 *
	 * @param kind      Which flow this result belongs to.
	 * @param requestId Correlation id from the request.
	 * @param response  Command output.
	 * @param fileName  File name when the command returned a file, otherwise null.
	 */
	public record CommandResult(RpcKind kind, String requestId, String response, String fileName) implements Packet {

		@Override
		public PacketType type() {
			return PacketType.COMMAND_RESULT;
		}

		/**
		 * Builds a result without a file payload.
		 */
		public static CommandResult text(RpcKind kind, String requestId, String response) {
			return new CommandResult(kind, requestId, response, null);
		}

		public boolean hasFile() {
			return fileName != null && !fileName.isBlank();
		}
	}

	/**
	 * One frame of a file payload streamed alongside a {@link CommandResult}.
	 *
	 * @param requestId Correlation id of the command that produced the file.
	 * @param fileName  File name, repeated on every chunk so the receiver can validate the stream.
	 * @param index     Zero based chunk index.
	 * @param total     Total number of chunks.
	 * @param data      Base64 encoded bytes of this chunk.
	 */
	public record CommandFileChunk(String requestId, String fileName, int index, int total,
								   String data) implements Packet {

		/**
		 * Raw bytes per chunk. Base64 inflates this by 4/3, so one frame stays far below the 1 MiB limit.
		 */
		public static final int CHUNK_BYTES = 256 * 1024;

		@Override
		public PacketType type() {
			return PacketType.COMMAND_FILE_CHUNK;
		}

		/**
		 * Splits a file payload into frames.
		 *
		 * @param requestId Correlation id of the command.
		 * @param fileName  File name.
		 * @param data      File bytes.
		 * @return One chunk per frame, in order. Empty when there is nothing to send.
		 */
		public static List<CommandFileChunk> split(String requestId, String fileName, byte[] data) {
			if (data == null || data.length == 0) {
				return List.of();
			}
			int total = (data.length + CHUNK_BYTES - 1) / CHUNK_BYTES;
			List<CommandFileChunk> chunks = new ArrayList<>(total);
			Base64.Encoder encoder = Base64.getEncoder();
			for (int index = 0; index < total; index++) {
				int offset = index * CHUNK_BYTES;
				int length = Math.min(CHUNK_BYTES, data.length - offset);
				chunks.add(new CommandFileChunk(requestId, fileName, index, total,
						encoder.encodeToString(Arrays.copyOfRange(data, offset, offset + length))));
			}
			return chunks;
		}
	}

	/**
	 * An auto-complete request.
	 *
	 * @param kind    Which command language to complete ({@code CONSOLE} or {@code EXECUTE}).
	 * @param input   Raw input to complete.
	 * @param opLevel Requester's OP level.
	 */
	public record AutoCompleteRequest(RpcKind kind, String input, int opLevel) implements Packet {
		@Override
		public PacketType type() {
			return PacketType.AUTOCOMPLETE_REQUEST;
		}
	}

	/**
	 * An auto-complete response.
	 *
	 * @param kind        Which command language was completed.
	 * @param suggestions Suggested completions.
	 */
	public record AutoCompleteResult(RpcKind kind, List<String> suggestions) implements Packet {
		@Override
		public PacketType type() {
			return PacketType.AUTOCOMPLETE_RESULT;
		}
	}

	// --- Runtime info ----------------------------------------------------------------------------

	/**
	 * Request for a runtime info snapshot.
	 *
	 * @param requestId    Correlation id, echoed by the {@link InfoSnapshot} that answers this request.
	 * @param sentAtMillis Sender timestamp, echoed so the receiver can measure round-trip latency.
	 */
	public record InfoRequest(long requestId, long sentAtMillis) implements Packet {
		@Override
		public PacketType type() {
			return PacketType.INFO_REQUEST;
		}
	}

	/**
	 * Runtime info of one DMCC client. {@code requestId} is copied from the {@link InfoRequest} being
	 * answered, so the server can tell the answer to this round from a late answer to an earlier one.
	 */
	public record InfoSnapshot(long requestId, String serverName, long connectionLatencyMillis, String minecraftVersion,
							   int onlinePlayerCount, int maxPlayerCount, Map<String, Integer> playersAndLatencies,
							   int playersEverJoined, double tps, double mspt, long uptimeSeconds,
							   long totalMemory, long freeMemory) implements Packet {
		@Override
		public PacketType type() {
			return PacketType.INFO_SNAPSHOT;
		}

		public InfoSnapshot withServerName(String serverName) {
			return new InfoSnapshot(requestId, serverName, connectionLatencyMillis, minecraftVersion, onlinePlayerCount,
					maxPlayerCount, playersAndLatencies, playersEverJoined, tps, mspt, uptimeSeconds, totalMemory, freeMemory);
		}

		public InfoSnapshot withMinecraftVersion(String minecraftVersion) {
			return new InfoSnapshot(requestId, serverName, connectionLatencyMillis, minecraftVersion, onlinePlayerCount,
					maxPlayerCount, playersAndLatencies, playersEverJoined, tps, mspt, uptimeSeconds, totalMemory, freeMemory);
		}

		public InfoSnapshot withRequestId(long requestId) {
			return new InfoSnapshot(requestId, serverName, connectionLatencyMillis, minecraftVersion, onlinePlayerCount,
					maxPlayerCount, playersAndLatencies, playersEverJoined, tps, mspt, uptimeSeconds, totalMemory, freeMemory);
		}

		public InfoSnapshot withConnectionLatency(long connectionLatencyMillis) {
			return new InfoSnapshot(requestId, serverName, connectionLatencyMillis, minecraftVersion, onlinePlayerCount,
					maxPlayerCount, playersAndLatencies, playersEverJoined, tps, mspt, uptimeSeconds, totalMemory, freeMemory);
		}
	}

	// --- Account linking -------------------------------------------------------------------------

	/**
	 * Request to create or re-check a link code. {@code joinCheck} marks the silent pre-check DMCC runs\n	 * when a player joins, as opposed to an explicit {@code /dmcc link}.\n	 */
	public record LinkRequest(String minecraftUuid, String playerName, boolean joinCheck) implements Packet {
		@Override
		public PacketType type() {
			return PacketType.LINK_REQUEST;
		}
	}

	/**
	 * Response to a {@link LinkRequest}. {@code code} is null when the player is already linked, in which\n	 * case {@code discordName} names the Discord account they are linked to.\n	 */
	public record LinkResult(String minecraftUuid, String code, boolean alreadyLinked,
							 String discordName) implements Packet {
		@Override
		public PacketType type() {
			return PacketType.LINK_RESULT;
		}
	}

	/**
	 * Request to unlink a player account.\n	 */
	public record UnlinkRequest(String minecraftUuid, String playerName) implements Packet {
		@Override
		public PacketType type() {
			return PacketType.UNLINK_REQUEST;
		}
	}

	/**
	 * Response to an {@link UnlinkRequest}; {@code discordName} is the account that was unlinked from.\n	 */
	public record UnlinkResult(String minecraftUuid, boolean success, String discordName) implements Packet {
		@Override
		public PacketType type() {
			return PacketType.UNLINK_RESULT;
		}
	}

	/**
	 * Full OP level synchronization payload: Minecraft UUID to OP level.\n	 */
	public record OpSync(Map<String, Integer> opLevels) implements Packet {
		@Override
		public PacketType type() {
			return PacketType.OP_SYNC;
		}
	}

	// --- Events ----------------------------------------------------------------------------------

	/**
	 * Discord events relayed to Minecraft.
	 */
	public enum DiscordEventType {
		CHAT,
		COMMAND,
		REACTION,
		EDIT,
		DELETE
	}

	/**
	 * Relays a parsed Discord event to the Minecraft side. {@code editedMessageSegments} is only set for\n	 * {@code EDIT}, and the mention fields are only set when somebody was actually mentioned.\n	 */
	public record DiscordRelay(DiscordEventType eventType, List<TextSegment> segments, List<TextSegment> replySegments,
							   List<TextSegment> editedMessageSegments, String mentionNotificationText,
							   String mentionNotificationStyle, List<String> mentionedPlayerUuids,
							   boolean mentionEveryone) implements Packet {

		@Override
		public PacketType type() {
			return PacketType.DISCORD_RELAY;
		}

		/**
		 * Convenience constructor for events without reply, edit or mention data.\n		 */
		public DiscordRelay(DiscordEventType eventType, List<TextSegment> segments) {
			this(eventType, segments, null, null, null, null, null, false);
		}
	}

	/**
	 * Relays a Minecraft-originated message back to Minecraft clients. When {@code componentJson} is set,\n	 * the receiver rebuilds the native component and swaps it in for {@code componentPlaceholder};\n	 * {@code componentText} is the plain-text fallback for clients that cannot.\n	 */
	public record MinecraftRelay(List<TextSegment> segments, String componentJson, String componentPlaceholder,
								 String componentText, String mentionNotificationText, String mentionNotificationStyle,
								 List<String> mentionedPlayerUuids, boolean mentionEveryone) implements Packet {

		@Override
		public PacketType type() {
			return PacketType.MINECRAFT_RELAY;
		}

		/**
		 * Convenience constructor for relays without component or mention data.\n		 */
		public MinecraftRelay(List<TextSegment> segments) {
			this(segments, null, null, null, null, null, null, false);
		}
	}

	/**
	 * Minecraft event kinds that Discord broadcast templates can render.
	 */
	public enum MinecraftEventType {
		SERVER_STARTED,
		SERVER_STOPPING,
		PLAYER_JOIN,
		PLAYER_QUIT,
		PLAYER_CHAT,
		PLAYER_COMMAND,
		PLAYER_DIE,
		PLAYER_ADVANCEMENT,
		PLAYER_CHANGE_GAME_MODE,
		SOURCE_SAY,
		SOURCE_TELL_RAW,
		SOURCE_MSG,
		SOURCE_ME
	}

	/**
	 * Carries Minecraft event placeholders for Discord-side templating.\n	 */
	public record MinecraftEvent(MinecraftEventType eventType, Map<String, String> placeholders) implements Packet {
		@Override
		public PacketType type() {
			return PacketType.MINECRAFT_EVENT;
		}
	}

	/**
	 * A batch of console log lines.\n	 */
	public record ConsoleLogBatch(List<String> lines) implements Packet {
		@Override
		public PacketType type() {
			return PacketType.CONSOLE_LOG_BATCH;
		}
	}
}
