blank_issues_enabled: false
contact_links:
  - name: Example Issue
    url: https://github.com/Xujiayao/Discord-MC-Chat/issues/73
    about: You can refer to this example issue to fill in your issue.
  - name: Discord-MC-Chat Docs
    url: https://blog.xujiayao.com/posts/4ba0a17a/
    about: Make sure you follow the docs to configure Discord-MC-Chat!
  - name: Latest Builds
    url: https://github.com/Xujiayao/Discord-MC-Chat/actions
    about: You can find the latest build JAR files at GitHub Actions.
  - name: DMCC Discord Server
    url: https://discord.gg/kbXkV6k2XU
    about: You can ask me questions on the DMCC Discord Server.