# ==================================================
# Discord-MC-Chat (DMCC)
# By Xujiayao
#
# Custom Messages file for DMCC version:
version: 3.0.0-beta.0
#
# Code:     zh_cn
# Language: 简体中文（中国大陆）
#
# More information + Docs:
# https://dmcc.xujiayao.com/
#
# Only edit the items below if you know what you are doing!
# ==================================================

templates: # You can add your own templates here
  - name: default
    with_webhook:
      multi_server_enabled:
        username: "[{server}] {display_name}"
        content: "{message}"
      multi_server_disabled:
        username: "{display_name}"
        content: "{message}"
    without_webhook:
      multi_server_enabled: "[{server}] <{display_name}> {message}"
      multi_server_disabled: "<{display_name}> {message}"

common:
  chat:
    - text: "[{server}] "
      bold: true
      color: "{server_color}"
    - text: "<{name}> "
      bold: false
      color: "{role_color}"
    - text: "{message}"
      bold: false
      color: "gray"
  others:
    - text: "[{server}] "
      bold: true
      color: "{server_color}"
    - text: "{message}"
      bold: false
      color: "gray"

discord_to_minecraft:
  response:
    - text: "    ┌──── "
      bold: true
      color: "dark_gray"
    - text: "<{name}> "
      bold: false
      color: "{role_color}"
    - text: "{message}"
      bold: false
      color: "dark_gray"
  command:
    - text: "[Discord] "
      bold: true
      color: "blue"
    - text: "<{name}> "
      bold: false
      color: "{role_color}"
    - text: "执行了 {command} 命令！"
      bold: false
      color: "gray"

minecraft_to_discord:
  server:
    start: "**服务器已启动！**"
    stop: "**服务器已关闭！**"
  player:
    join: "**{display_name} 加入了游戏**"
    quit: "**{display_name} 离开了游戏**"
    chat: default
    command: default
    die: "**{death_message}**"
    advancement:
      task: "**{display_name} 达成了进度 [{advancement}]**\n*{description}*"
      challenge: "**{display_name} 完成了挑战 [{advancement}]**\n*{description}*"
      goal: "**{display_name} 达成了目标 [{advancement}]**\n*{description}*"
  source:
    say: default
    tell_raw: default

channel_topic_updating:
  offline: ":x: 服务器离线 | 最后更新于：<t:{last_update_time}:f>"
  online:
    multi_server_enabled: ":white_check_mark: {online_player_count}/{max_player_count} 位玩家在线 | {total_player_count} 位玩家曾加入过 | {online_server_count} 个服务器在线 [{online_server_list}] | 服务器启动于 <t:{server_started_time}:R> | 最后更新于：<t:{last_update_time}:f>"
    multi_server_disabled: ":white_check_mark: {online_player_count}/{max_player_count} 位玩家在线 | {total_player_count} 位玩家曾加入过 | 服务器启动于 <t:{server_started_time}:R> | 最后更新于：<t:{last_update_time}:f>"

mspt_monitoring:
  high_mspt: "**服务器 MSPT ({mspt}) 高于 {mspt_limit}！**"
