# ==================================================
# Discord-MC-Chat (DMCC)
# By Xujiayao
#
# Custom Messages file for DMCC version:
# Do NOT change this value manually!
version: ${mod_version}
#
# Code:     en_us
# Language: English (US)
#
# Discord-MC-Chat Docs:
# https://dmcc.xujiayao.com/
#
# Only edit the items below if you know what you are doing!
# ==================================================

xxxxx_to_minecraft: # for both discord_to_minecraft and minecraft_to_minecraft
  user_message:
    - text: "[{server}] "
      bold: true
      color: "{server_color}"
    - text: "<{effective_name}> "
      bold: false
      color: "{role_color}"
    - text: "{message}"
      bold: false
      color: "gray"
  system_message:
    - text: "[{server}] "
      bold: true
      color: "{server_color}"
    - text: "{message}"
      bold: false
      color: "gray"

overwrite:
  standalone:
    user_message:
      - text: "[{server}] "
        bold: true
        color: "{server_color}"
      - text: "<{display_name}> "
        bold: false
        color: "{role_color}"
      - text: "{message}"
        bold: false
        color: "white"
    system_message:
      - text: "[{server}] "
        bold: true
        color: "{server_color}"
      - text: "{message}"
        bold: false
        color: "white"
  single_server:
    user_message:
      - text: "<{display_name}> "
        bold: false
        color: "{role_color}"
      - text: "{message}"
        bold: false
        color: "white"
    system_message:
      - text: "{message}"
        bold: false
        color: "white"

discord_to_minecraft:
  mentioned: "{effective_name} mentioned you!"
  response: # 回复其它用户的消息时，原消息的格式
    - text: "    ┌──── "
      bold: true
      color: "dark_gray"
    - text: "<{effective_name}> "
      bold: false
      color: "{role_color}"
    - text: "{message}"
      bold: false
      color: "dark_gray"
  command:
    - text: "[Discord] "
      bold: true
      color: "blue"
    - text: "{effective_name} "
      bold: false
      color: "{role_color}"
    - text: "executed [{command}] command!"
      bold: false
      color: "gray"
  reaction: # Reaction message format
    - text: "[Discord] "
      bold: true
      color: "blue"
    - text: "{effective_name} "
      bold: false
      color: "{role_color}"
    - text: "reacted "
      bold: false
      color: "gray"
    - text: "{emoji}"
      bold: false
      color: "yellow"
    - text: " to this message!"
      bold: false
      color: "gray"
  edit: # Message edit notification format
    - text: "[Discord] "
      bold: true
      color: "blue"
    - text: "{effective_name} "
      bold: false
      color: "{role_color}"
    - text: "edited this message! Edited message becomes:"
      bold: false
      color: "gray"
  edited_message: # Edited message content format
    - text: "    └──── "
      bold: true
      color: "dark_gray"
    - text: "<{effective_name}> "
      bold: false
      color: "{role_color}"
    - text: "{message}"
      bold: false
      color: "gray"
  delete: # Message delete notification format
    - text: "[Discord] "
      bold: true
      color: "blue"
    - text: "A message sent by "
      bold: false
      color: "gray"
    - text: "{effective_name} "
      bold: false
      color: "{role_color}"
    - text: "has been deleted!"
      bold: false
      color: "gray"

minecraft_to_xxxxx:
  server:
    start: ":white_check_mark: **Server started!**"
    stop: ":octagonal_sign: **Server stopped!**"
  player:
    join: ":wave: **{display_name} joined the server**"
    quit: ":cry: **{display_name} left the server**"
    die: ":skull: **{death_message}**"
    advancement:
      task: ":partying_face: **{display_name} has made the advancement [{title}]**\\n       *{description}*"
      challenge: ":partying_face: **{display_name} has completed the challenge [{title}]**\\n       *{description}*"
      goal: ":partying_face: **{display_name} has reached the goal [{title}]**\\n       *{description}*"
    change_game_mode: ":arrows_counterclockwise: **{display_name} changed game mode to {mode}**"
  source:
    me: ":eyes: **{display_name} {action}**"

minecraft_to_discord:
  user_message:
    enabled_fake_user_style:
      standalone:
        username: "[{server}] {display_name}"
        content: "{message}"
      single_server:
        username: "{display_name}"
        content: "{message}"
    disabled_fake_user_style:
      standalone: "[{server}] <{display_name}> {message}" # should still use each DMCC clients webhook to send
      single_server: "<{display_name}> {message}"

activity:
  all_servers_offline: "Minecraft (server offline)"
  at_least_one_server_online: "Minecraft ({online_player_count}/{max_player_count})"

channel_topic_updating:
  all_servers_offline: ":octagonal_sign: Server offline | Last updated: <t:{last_update_time}:f>"
  at_least_one_server_online:
    standalone: ":white_check_mark: {online_player_count}/{max_player_count} player(s) online | {total_player_count} player(s) ever joined | {online_server_count} server(s) online [{online_server_list}] | Server started <t:{server_started_time}:R> | Last updated: <t:{last_update_time}:f>"
    single_server: ":white_check_mark: {online_player_count}/{max_player_count} player(s) online | {total_player_count} player(s) ever joined | Server started <t:{server_started_time}:R> | Last updated: <t:{last_update_time}:f>"

mspt_monitoring:
  high_mspt: ":warning: **Server MSPT has reached {mspt}!**"
