# ==================================================
# Discord-MC-Chat (DMCC)
# By Xujiayao
#
# Custom Messages file for DMCC version:
# Do NOT change this value manually!
version: ${mod_version}
#
# Code:     en_us
# Language: English (US)
#
# Discord-MC-Chat Docs:
# https://dmcc.xujiayao.com/
#
# Only edit the items below if you know what you are doing!
# ==================================================

templates: # You can add your own templates here
  - name: default
    with_webhook:
      standalone:
        username: "[{server}] {display_name}"
        content: "{message}"
      single_server:
        username: "{display_name}"
        content: "{message}"
    without_webhook:
      standalone: "[{server}] <{display_name}> {message}"
      single_server: "<{display_name}> {message}"

common:
  chat:
    - text: "[{server}] "
      bold: true
      color: "{server_color}"
    - text: "<{effective_name}> "
      bold: false
      color: "{role_color}"
    - text: "{message}"
      bold: false
      color: "gray"
  others:
    - text: "[{server}] "
      bold: true
      color: "{server_color}"
    - text: "{message}"
      bold: false
      color: "gray"

discord_to_minecraft:
  chat:
    - text: "[Discord] "
      bold: true
      color: "blue"
    - text: "<{effective_name}> "
      bold: false
      color: "{role_color}"
    - text: "{message}"
      bold: false
      color: "gray"
  mentioned: "{effective_name} mentioned you!"
  response:  # 回复其它用户的消息时，原消息的格式
    - text: "    ┌──── "
      bold: true
      color: "dark_gray"
    - text: "<{effective_name}> "
      bold: false
      color: "{role_color}"
    - text: "{message}"
      bold: false
      color: "dark_gray"
  command:
    - text: "[Discord] "
      bold: true
      color: "blue"
    - text: "{effective_name} "
      bold: false
      color: "{role_color}"
    - text: "executed [{command}] command!"
      bold: false
      color: "gray"

minecraft_to_discord:
  server:
    start: ":white_check_mark: **Server started!**"
    stop: ":octagonal_sign: **Server stopped!**"
  player:
    join: ":wave: **{display_name} joined the server**"
    quit: ":cry: **{display_name} left the server**"
    chat: default
    command: default
    die: ":skull: **{death_message}**"
    advancement:
      task: ":partying_face: **{display_name} has made the advancement [{title}]**\\n       *{description}*"
      challenge: ":partying_face: **{display_name} has completed the challenge [{title}]**\\n       *{description}*"
      goal: ":partying_face: **{display_name} has reached the goal [{title}]**\\n       *{description}*"
  source:
    say: default
    tell_raw: default

activity:
  all_servers_offline: "Minecraft (server offline)"
  at_least_one_server_online: "Minecraft ({online_player_count}/{max_player_count})"

channel_topic_updating:
  all_servers_offline: ":octagonal_sign: Server offline | Last updated: <t:{last_update_time}:f>"
  at_least_one_server_online:
    standalone: ":white_check_mark: {online_player_count}/{max_player_count} player(s) online | {total_player_count} player(s) ever joined | {online_server_count} server(s) online [{online_server_list}] | Server started <t:{server_started_time}:R> | Last updated: <t:{last_update_time}:f>"
    single_server: ":white_check_mark: {online_player_count}/{max_player_count} player(s) online | {total_player_count} player(s) ever joined | Server started <t:{server_started_time}:R> | Last updated: <t:{last_update_time}:f>"

mspt_monitoring:
  high_mspt: ":warning: **Server MSPT has reached {mspt}!**"
