# ==================================================
# Discord-MC-Chat (DMCC)
# By Xujiayao
#
# Custom Messages file for DMCC version:
# Do NOT change this value manually!
version: ${mod_version}
#
# Code:     zh_cn
# Language: 简体中文（中国大陆）
#
# Discord-MC-Chat Docs:
# https://dmcc.xujiayao.com/
#
# Only edit the items below if you know what you are doing!
# ==================================================

xxxxx_to_minecraft: # for both discord_to_minecraft and minecraft_to_minecraft
  mentioned: "{effective_name} 提及了你！"
  user_message:
    - text: "[{server}] "
      bold: true
      color: "{server_color}"
    - text: "<{effective_name}> "
      bold: false
      color: "{role_color}"
    - text: "{message}"
      bold: false
      color: "gray"
  system_message:
    - text: "[{server}] "
      bold: true
      color: "{server_color}"
    - text: "{message}"
      bold: false
      color: "gray"

overwrite: # for source DMCC client only
  standalone:
    user_message:
      - text: "[{server}] "
        bold: true
        color: "{server_color}"
      - text: "<{display_name}> "
        bold: false
        color: "{role_color}"
      - text: "{message}"
        bold: false
        color: "white"
    system_message:
      - text: "[{server}] "
        bold: true
        color: "{server_color}"
      - text: "{message}"
        bold: false
        color: "white"
  single_server:
    user_message:
      - text: "<{display_name}> "
        bold: false
        color: "{role_color}"
      - text: "{message}"
        bold: false
        color: "white"
    system_message:
      - text: "{message}"
        bold: false
        color: "white"

discord_to_minecraft:
  response: # 回复其它用户的消息时，原消息的格式
    - text: "    ┌──── "
      bold: true
      color: "dark_gray"
    - text: "<{effective_name}> "
      bold: false
      color: "{role_color}"
    - text: "{message}"
      bold: false
      color: "dark_gray"
  command:
    - text: "[Discord] "
      bold: true
      color: "blue"
    - text: "{effective_name} "
      bold: false
      color: "{role_color}"
    - text: "执行了 [{command}] 命令！"
      bold: false
      color: "gray"
  reaction: # 表情反应消息格式
    - text: "[Discord] "
      bold: true
      color: "blue"
    - text: "{effective_name} "
      bold: false
      color: "{role_color}"
    - text: "对此消息做出了 "
      bold: false
      color: "gray"
    - text: "{emoji}"
      bold: false
      color: "yellow"
    - text: " 反应！"
      bold: false
      color: "gray"
  edit: # 消息编辑通知格式
    - text: "[Discord] "
      bold: true
      color: "blue"
    - text: "{effective_name} "
      bold: false
      color: "{role_color}"
    - text: "编辑了此消息！编辑后的消息为："
      bold: false
      color: "gray"
  edited_message: # 编辑后的消息内容格式
    - text: "    └──── "
      bold: true
      color: "dark_gray"
    - text: "<{effective_name}> "
      bold: false
      color: "{role_color}"
    - text: "{message}"
      bold: false
      color: "gray"
  delete: # 消息删除通知格式
    - text: "[Discord] "
      bold: true
      color: "blue"
    - text: "{effective_name} "
      bold: false
      color: "{role_color}"
    - text: "发送的消息已被删除！"
      bold: false
      color: "gray"

# These are for system_messages
minecraft_to_xxxxx:
  server:
    start: ":white_check_mark: **服务器已启动！**"
    stop: ":octagonal_sign: **服务器已关闭！**"
  player:
    join: ":wave: **{display_name} 加入了服务器**"
    quit: ":cry: **{display_name} 离开了服务器**"
    die: ":skull: **{death_message}**"
    advancement:
      task: ":partying_face: **{display_name} 取得了进度 [{title}]**\\n       *{description}*"
      challenge: ":partying_face: **{display_name} 完成了挑战 [{title}]**\\n       *{description}*"
      goal: ":partying_face: **{display_name} 达成了目标 [{title}]**\\n       *{description}*"
    change_game_mode: ":arrows_counterclockwise: **{display_name} 切换游戏模式为 {mode}**"
  source:
    me: ":eyes: **{action}**"

# These are for user_messages
minecraft_to_discord:
  user_message:
    enabled_fake_user_style:
      standalone:
        username: "[{server}] {display_name}"
        content: "{message}"
      single_server:
        username: "{display_name}"
        content: "{message}"
    disabled_fake_user_style:
      standalone: "[{server}] <{display_name}> {message}" # should still use each DMCC clients webhook to send
      single_server: "<{display_name}> {message}"

activity:
  all_servers_offline: "Minecraft (服务器离线)"
  at_least_one_server_online: "Minecraft ({online_player_count}/{max_player_count})"

channel_topic_updating:
  all_servers_offline: ":octagonal_sign: 服务器离线 | 最后更新于：<t:{last_update_time}:f>"
  at_least_one_server_online:
    standalone: ":white_check_mark: {online_player_count}/{max_player_count} 位玩家在线 | {players_ever_joined} 位玩家曾加入过 | {online_server_count} 个服务器在线 [{online_server_list}] | 服务器启动于 <t:{server_started_time}:R> | 最后更新于：<t:{last_update_time}:f>"
    single_server: ":white_check_mark: {online_player_count}/{max_player_count} 位玩家在线 | {players_ever_joined} 位玩家曾加入过 | 服务器启动于 <t:{server_started_time}:R> | 最后更新于：<t:{last_update_time}:f>"

voice_channels_updating:
  server_status:
    all_servers_offline: "状态：离线"
    at_least_one_server_online:
      standalone: "状态：{online_server_count} 个服务器在线"
      single_server: "状态：在线"
  player_count:
    all_servers_offline: "玩家：0"
    at_least_one_server_online: "玩家：{online_player_count}/{max_player_count}"

mspt_monitoring:
  first_exceeded: ":warning: **服务器 MSPT ({mspt}) 超过阈值 ({threshold})！下次检查将在 <t:{next_check_time}:R> 进行。**"
  still_exceeded: ":warning: **服务器 MSPT ({mspt}) 仍超过阈值 ({threshold})！下次检查将在 <t:{next_check_time}:R> 进行。**"
  first_recovered: ":white_check_mark: **服务器 MSPT ({mspt}) 已恢复到阈值 ({threshold}) 以下！**"

console_forwarding:
  started:
    standalone: ":white_check_mark: :satellite: **已开始转发来自 {server} 的控制台日志！**"
    single_server: ":white_check_mark: :satellite: **已开始转发控制台日志！**"
  stopped:
    standalone: ":octagonal_sign: :satellite: **已停止转发来自 {server} 的控制台日志！**"
    single_server: ":octagonal_sign: :satellite: **已停止转发控制台日志！**"
