# ==================================================
# Discord-MC-Chat (DMCC)
# By Xujiayao
#
# Custom Messages file for DMCC version:
# Do NOT change this value manually!
version: ${mod_version}
#
# Code:     zh_cn
# Language: 简体中文（中国大陆）
#
# Discord-MC-Chat Docs:
# https://dmcc.xujiayao.com/
#
# Only edit the items below if you know what you are doing!
# ==================================================

xxxxx_to_minecraft: # for both discord_to_minecraft and between_minecraft_servers
  user_message:
    - text: "[{server}] "
      bold: true
      color: "{server_color}"
    - text: "<{effective_name}> "
      bold: false
      color: "{role_color}"
    - text: "{message}"
      bold: false
      color: "gray"
  system_message:
    - text: "[{server}] "
      bold: true
      color: "{server_color}"
    - text: "{message}"
      bold: false
      color: "gray"

discord_to_minecraft:
  mentioned: "{effective_name} 提及了你！"
  response: # 回复其它用户的消息时，原消息的格式
    - text: "    ┌──── "
      bold: true
      color: "dark_gray"
    - text: "<{effective_name}> "
      bold: false
      color: "{role_color}"
    - text: "{message}"
      bold: false
      color: "dark_gray"
  command:
    - text: "[Discord] "
      bold: true
      color: "blue"
    - text: "{effective_name} "
      bold: false
      color: "{role_color}"
    - text: "执行了 [{command}] 命令！"
      bold: false
      color: "gray"
  reaction: # 表情反应消息格式
    - text: "[Discord] "
      bold: true
      color: "blue"
    - text: "{effective_name} "
      bold: false
      color: "{role_color}"
    - text: "对此消息做出了 "
      bold: false
      color: "gray"
    - text: "{emoji}"
      bold: false
      color: "yellow"
    - text: " 反应！"
      bold: false
      color: "gray"
  edit: # 消息编辑通知格式
    - text: "[Discord] "
      bold: true
      color: "blue"
    - text: "{effective_name} "
      bold: false
      color: "{role_color}"
    - text: "编辑了此消息！编辑后的消息为："
      bold: false
      color: "gray"
  edited_message: # 编辑后的消息内容格式
    - text: "    └──── "
      bold: true
      color: "dark_gray"
    - text: "<{effective_name}> "
      bold: false
      color: "{role_color}"
    - text: "{message}"
      bold: false
      color: "gray"
  delete: # 消息删除通知格式
    - text: "[Discord] "
      bold: true
      color: "blue"
    - text: "{effective_name} "
      bold: false
      color: "{role_color}"
    - text: "发送的消息已被删除！"
      bold: false
      color: "gray"

minecraft_to_xxxxx:
  server:
    start: ":white_check_mark: **服务器已启动！**"
    stop: ":octagonal_sign: **服务器已关闭！**"
  player:
    join: ":wave: **{display_name} 加入了服务器**"
    quit: ":cry: **{display_name} 离开了服务器**"
    die: ":skull: **{death_message}**"
    advancement:
      task: ":partying_face: **{display_name} 取得了进度 [{title}]**\\n       *{description}*"
      challenge: ":partying_face: **{display_name} 完成了挑战 [{title}]**\\n       *{description}*"
      goal: ":partying_face: **{display_name} 达成了目标 [{title}]**\\n       *{description}*"
    change_game_mode: ":arrows_counterclockwise: **{display_name} 切换游戏模式为 {mode}**"
  source:
    me: ":eyes: **{display_name} {action}**"

minecraft_to_discord:
  user_message:
    enabled_fake_user_style:
      standalone:
        username: "[{server}] {display_name}"
        content: "{message}"
      single_server:
        username: "{display_name}"
        content: "{message}"
    disabled_fake_user_style:
      standalone: "[{server}] <{display_name}> {message}" # should still use each DMCC clients webhook to send
      single_server: "<{display_name}> {message}"

activity:
  all_servers_offline: "Minecraft (服务器离线)"
  at_least_one_server_online: "Minecraft ({online_player_count}/{max_player_count})"

channel_topic_updating:
  all_servers_offline: ":octagonal_sign: 服务器离线 | 最后更新于：<t:{last_update_time}:f>"
  at_least_one_server_online:
    standalone: ":white_check_mark: {online_player_count}/{max_player_count} 位玩家在线 | {total_player_count} 位玩家曾加入过 | {online_server_count} 个服务器在线 [{online_server_list}] | 服务器启动于 <t:{server_started_time}:R> | 最后更新于：<t:{last_update_time}:f>"
    single_server: ":white_check_mark: {online_player_count}/{max_player_count} 位玩家在线 | {total_player_count} 位玩家曾加入过 | 服务器启动于 <t:{server_started_time}:R> | 最后更新于：<t:{last_update_time}:f>"

mspt_monitoring:
  high_mspt: ":warning: **服务器 MSPT 已达 {mspt}！**"
