package com.xujiayao.discord_mc_chat.network.packets;

public final class AuthPackets {
	private AuthPackets() {
	}

	/**
	 * Sent by client with the calculated hash.
	 */
	public static final class AuthResponsePacket extends Packet {
		/**
		 * SHA-256 hash computed from challenge salt and shared secret.
		 */
		public final String hash;

		public AuthResponsePacket(String hash) {
			this.hash = hash;
		}
	}

	/**
	 * Sent by server to challenge the client.
	 */
	public static final class ChallengePacket extends Packet {
		/**
		 * Random challenge salt generated by server.
		 */
		public final String salt;

		public ChallengePacket(String salt) {
			this.salt = salt;
		}
	}

	/**
	 * Sent by either side to disconnect with a localized reason.
	 */
	public static final class DisconnectPacket extends Packet {
		/**
		 * Translation key for disconnect reason.
		 */
		public final String key;
		/**
		 * Translation arguments for disconnect reason.
		 */
		public final Object[] args;

		public DisconnectPacket(String key, Object... args) {
			this.key = key;
			this.args = args;
		}
	}

	/**
	 * Sent by client to initiate connection.
	 */
	public static final class HandshakePacket extends Packet {
		/**
		 * DMCC client/server name.
		 */
		public final String serverName;
		/**
		 * DMCC version of the sender.
		 */
		public final String dmccVersion;
		/**
		 * Minecraft version of the sender environment.
		 */
		public final String minecraftVersion;

		public HandshakePacket(String serverName, String dmccVersion, String minecraftVersion) {
			this.serverName = serverName;
			this.dmccVersion = dmccVersion;
			this.minecraftVersion = minecraftVersion;
		}
	}

	/**
	 * Sent by server to confirm authentication success.
	 */
	public static final class LoginSuccessPacket extends Packet {
		/**
		 * Selected language code sent by server.
		 */
		public final String language;
		/**
		 * Whether Minecraft source messages should be overwritten.
		 */
		public final boolean overwriteMinecraftSourceMessages;
		/**
		 * Whether console forwarding is enabled.
		 */
		public final boolean consoleForwardingEnabled;

		public LoginSuccessPacket(String language, boolean overwriteMinecraftSourceMessages, boolean consoleForwardingEnabled) {
			this.language = language;
			this.overwriteMinecraftSourceMessages = overwriteMinecraftSourceMessages;
			this.consoleForwardingEnabled = consoleForwardingEnabled;
		}
	}
}
