# ==================================================
# Discord-MC-Chat (DMCC)
# By Xujiayao
#
# Config file for DMCC version:
version: 3.0.0-beta.0
#
# More information + Docs:
# https://dmcc.xujiayao.com/
# ==================================================

# 语言设置
language: en_us

# 机器人设置
bot:
  token: # Discord 机器人令牌
  rich_presence: # TODO
    enable: true
    todo: true

# 关闭设置
shutdown:
  graceful_shutdown: true # 是否优雅关闭服务器

# Webhook 设置
webhook:
  enable: true # 是否使用 Webhook 发送聊天消息
  avatar_url: https://mc-heads.net/avatar/{player_uuid}.png
  allowed_mentions: # 允许 Webhook 触发提及的对象
    - everyone
    - users
    - roles

# 检查更新设置
check_for_updates:
  enable: true # 是否检查更新
  mention_admins: true # 是否在更新通知中提及管理员
  channel: in-game-chat

# 消息广播设置
broadcasts:
  discord_to_minecraft: # true or false
    chat: true
    command: true
  minecraft_to_discord: # channel name, empty = disable
    server:
      started: in-game-chat
      stopped: in-game-chat
    player:
      join: in-game-chat
      quit: in-game-chat
      chat: in-game-chat
      command: in-game-chat
      die: in-game-chat
      advancement: in-game-chat
    source:
      say: in-game-chat
      tell_raw: in-game-chat

# 多服务器功能
multi_server:
  for_standalone_mode_only:
    port: 5000
    servers:
      - name: SMP
        color: yellow
        start_command: ./SMP/start.bat # command or url
  for_minecraft_mod_mode_only:
    enable: false
    connection:
      host: localhost
      port: 5000
    server_name: SMP

# MSPT 监控设置
mspt_monitoring:
  enable: true
  interval_seconds: 5
  threshold: 50
  channel: in-game-chat

# 控制台转发设置
console_forwarding:
  enable: true
  execute_command: true
  channel: console_forwarding

# 管理员设置
dmcc_admin:
  minecraft_op_level_requirement: 4

# 账户绑定设置
# 强制启用，若MC里为某op_level，自动成为DMCC管理员，允许使用管理命令
account_linking:
  link_code_expires_in_seconds: 600
  features:
    sync_role_colors: true
    sync_op_level_based_on_discord_roles:
      enable: true
      list:
        - role_name: Admins
          op_level: 4
    discord_mention_notifications:
      enable: true
      style: action_bar # action_bar, title, or chat

# 频道主题更新设置
channel_topic_updating:
  enable: true
  interval_seconds: 600
  channel: in-game-chat

# 命令权限设置
command_permissions:
  help: everyone
  info: everyone
  stats: everyone
  link: everyone
  update: everyone
  whitelist: admin
  console: admin
  log: admin
  reload: admin
  start: admin
  stop: admin

# 消息格式设置
formatting: # TODO
  format_chat_messages: true
  todo: true

# 命令过滤设置
excluded_commands:
  - /msg (?!@a)(.*)
  - /tell (?!@a)(.*)
  - /tellraw (?!@a)(.*)
  - /w (?!@a)(.*)
  - /teammsg (.*)
  - /tm (.*)
  - /login (.*)
  - /l (.*)
  - /register (.*)
  - /reg (.*)
  - /account (.*)
  - /auth (.*)
