# ==================================================
# Discord-MC-Chat (DMCC)
# By Xujiayao
#
# Config file for DMCC version: 3.0.0-beta.0
#
# More information + Docs:
# https://blog.xujiayao.com/posts/4ba0a17a/
# ==================================================

# 语言设置
language: en_us

# 机器人设置
bot:
  token: # Discord 机器人令牌
  rich_presence: # TODO
    enable: true
    todo: true

# 关闭设置
shutdown:
  graceful_shutdown: true # 是否优雅关闭服务器

# Webhook 设置
webhook:
  enable: true # 是否使用 Webhook 发送聊天消息
  avatar_url: https://mc-heads.net/avatar/{player_uuid}.png
  allowed_mentions: # 允许 Webhook 触发提及的对象
    - everyone
    - users
    - roles

# 频道设置
channels: # You can add your own channels here
  - name: chat
    id: 1234567890
  - name: console_forwarding
    id: 1234567890

# 检查更新设置
check_for_updates:
  enable: true # 是否检查更新
  mention_admins: true # 是否在更新通知中提及管理员
  channel: chat

# 消息广播设置
broadcasts:
  discord_to_minecraft: # true or false
    chat: true
    command: true
  minecraft_to_discord: # channel name, empty = disable
    server:
      start: chat
      stop: chat
    player:
      join: chat
      quit: chat
      chat: chat
      command: chat
      die: chat
      advancement: chat
    source:
      say: chat
      tell_raw: chat

# 管理员设置
admins:
  - discord_username: xujiayao
    minecraft_op_level: 4

# 多服务器功能
multi_server:
  enable: false
  connection:
    host: localhost
    port: 5000
  server_name: SMP

# MSPT 监控设置
mspt_monitoring:
  enable: true
  interval_seconds: 5
  threshold: 50
  channel: chat

# 控制台转发设置
console_forwarding:
  enable: true
  execute_command: true
  channel: console_forwarding

# 账户绑定设置
account_linking:
  enable: true
  link_code_expires_in_seconds: 600
  features:
    sync_role_colors: true
    discord_mention_notifications:
      enable: true
      style: action_bar # action_bar, title, or chat

# 频道主题更新设置
channel_topic_updating:
  enable: true
  interval_seconds: 600
  channel: chat

# 命令权限设置
command_permissions:
  help: everyone
  info: everyone
  stats: everyone
  link: everyone
  update: everyone
  whitelist: admin
  console: admin
  log: admin
  reload: admin
  start: admin
  stop: admin

# 消息格式设置
formatting: # TODO
  format_chat_messages: true
  todo: true

# 命令过滤设置
excluded_commands:
  - /msg (?!@a)(.*)
  - /tell (?!@a)(.*)
  - /tellraw (?!@a)(.*)
  - /w (?!@a)(.*)
  - /teammsg (.*)
  - /tm (.*)
  - /login (.*)
  - /l (.*)
  - /register (.*)
  - /reg (.*)
  - /account (.*)
  - /auth (.*)

# --------------------------------------------------
# Only edit the items below if you know what you are doing!
# --------------------------------------------------

# 自定义消息
custom_messages:
  templates: # You can add your own templates here
    - default:
        with_webhook:
          multi_server_enabled:
            username: "[{server}] {display_name}"
            content: "{message}"
          multi_server_disabled:
            username: "{display_name}"
            content: "{message}"
        without_webhook:
          multi_server_enabled: "[{server}] <{display_name}> {message}"
          multi_server_disabled: "<{display_name}> {message}"
  discord_to_minecraft:
    chat: "<bold><blue>[Discord]<clear> <color {role_color}><{name}><clear> <gray>{message}<clear>"
    response: "<bold><dark_gray>    ┌────<clear> <color {role_color}><{name}><clear> <dark_gray>{message}<clear>"
    command: "<bold><blue>[Discord]<clear> <color {role_color}><{name}><clear> <gray>executed {message} command!<clear>"
  minecraft_to_discord:
    server:
      start: "**Server started!**"
      stop: "**Server stopped!**"
    player:
      join: "**{display_name} joined the game**"
      quit: "**{display_name} left the game**"
      chat: default
      command: default
      die: "**{death_message}**"
      advancement:
        task: "**{display_name} has made the advancement [{advancement}]**\n*{description}*"
        challenge: "**{display_name} has completed the challenge [{advancement}]**\n*{description}*"
        goal: "**{display_name} has reached the goal [{advancement}]**\n*{description}*"
    source:
      say: default
      tell_raw: default
  channel_topic_updating:
    offline: ":x: Server offline | Last updated: <t:{lastUpdateTime}:f>"
    online:
      multi_server_enabled: ":white_check_mark: {onlinePlayerCount}/{maxPlayerCount} player(s) online | {uniquePlayerCount} unique player(s) ever joined | {onlineServerCount} server(s) online [{onlineServerList}] | Server started <t:{serverStartedTime}:R> | Last updated: <t:{lastUpdateTime}:f>"
      multi_server_disabled: ":white_check_mark: {onlinePlayerCount}/{maxPlayerCount} player(s) online | {uniquePlayerCount} unique player(s) ever joined | Server started <t:{serverStartedTime}:R> | Last updated: <t:{lastUpdateTime}:f>"
  mspt_monitoring:
    high_mspt: "**Server MSPT ({mspt}) is above {msptLimit}!**"

# 配置文件版本，自行修改此项会导致无法正常初始化DMCC
config_version: 1
