license="MIT"
issueTrackerURL="https://github.com/Xujiayao/Discord-MC-Chat/issues"
displayURL="https://dmcc.xujiayao.com/"

[[mods]]
modId="discord_mc_chat"
version="${mod_version}"
displayName="Discord-MC-Chat"
authors="Xujiayao"
logoFile="icon/icon.png"
description='''
Discord-MC-Chat (DMCC), formerly known as MC-Discord-Chat and MCDiscordChat (MCDC), is a practical and powerful Fabric and NeoForge Minecraft <> Discord chat bridge inspired by BRForgers/DisFabric.
'''

# The mixin configuration is shared with the Fabric build and lives in the common module.
[[mixins]]
config="dmcc.mixins.json"

[[dependencies.discord_mc_chat]]
modId="neoforge"
type="required"
versionRange="${minecraft_version_range_neoforge}"
ordering="NONE"
side="BOTH"

[[dependencies.discord_mc_chat]]
modId="minecraft"
type="required"
versionRange="${minecraft_version_range_neoforge}"
ordering="NONE"
side="BOTH"
