# ==================================================
# Discord-MC-Chat (DMCC)
# By Xujiayao
#
# Config file for DMCC version & mode:
# Do NOT change these values manually!
version: ${mod_version}
mode: multi_server_client
#
# Discord-MC-Chat Docs:
# https://dmcc.xujiayao.com/
# ==================================================

multi_server:
  server_name: "your_server_name_here"
  connection:
    host: "127.0.0.1"
    port: 5000
    shared_secret: "your_shared_secret_here"

# Configure the minimum OP level required to run each command.
# Special value:
#   Level -1
#     Allow anyone to execute (including unlinked Discord users)
# Official Minecraft permission levels corresponding to OP levels:
#   Level 0 (normal)
#     Player has no special permissions.
#   Level 1 (moderator)
#     Player can bypass spawn protection.
#   Level 2 (gamemaster)
#     Player or executor can use more commands and player can use command blocks.
#   Level 3 (admin)
#     Player or executor can use commands related to multiplayer management.
#   Level 4 (owner)
#     Player or executor can use all the commands, including commands related to server management.
command_permission_levels:
  help: -1
  info: -1
  link: 0
  log: 4
  reload: 4
  stats: -1
  unlink: 0
  update: -1
  whitelist: 0

check_for_updates:
  enable: true
